### ISSUE TITLE
FrontEnd Keplr cannot connect

### ISSUE THREAD

**Issue by Alkia** [Alkia/electra#5]
Front End do not accept connection from Keplr

**Comment by ElectaZ** [comment]
Testing today

**Comment by ElectaZ** [comment]
Cannot reproduce directly

**Comment by ElectaZ** [comment]
To be retested later

**Comment by Alkia** [comment]
How is the results?

**Comment by Alkia** [comment]
Not ok yet, got some hints here

**Comment by Alkia** [comment]
done
